export {default as Navbar} from "./Navbar/Navbar.jsx"
export {default as Header} from "./Header/Header.jsx"
export {default as Feature} from "./Feature/Feature.jsx"
export {default as Collection} from "./Collection/Collection.jsx"
export {default as Products} from "./Products/Products.jsx"
export {default as Product} from "./Product/Product.jsx"
export {default as Footer} from "./Footer/Footer.jsx"